version: 0.1
            
phases:

  install: 
    commands:
      - go get -u github.com/golang/lint/golint

  pre_build: 
    commands:

      # Ensure code passes all lint tests
      - golint -set_exit_status

      # Uncomment when tests created to run all tests included with our application
      # - go test

  build:
    commands:

      # Build our application
      - go build -o app

artifacts:
  files:
    - app
    - buildspec.yml
    - assets/*
    - template.yml